install:
	cp example.js /usr/libexec
	cp org.dbus.example.conf /etc/dbus-1/system.d
	cp org.dbus.example.service /usr/share/dbus-1/system-services

uninstall:
	rm /usr/libexec/example.js
	rm /etc/dbus-1/system.d/org.dbus.example.conf
	rm /usr/share/dbus-1/system-services/org.dbus.example.service
